enum AuthUserType {
  ADMIN
  USER
}

type Auth {
  # Example field (placeholder)
  userId: Int
  userType: AuthUserType!
  email: String!
  fullName: String!
}

type AuthTokenInfo {
  accessToken: String!
  accessTokenExpiresAt: Int!
  refreshToken: String!
  refreshTokenExpiresAt: Int!
  tokenType: String!
}

extend type Query {
  auth(id: Int!): Auth
}

extend type Mutation {
  info: Auth!
  loginWithEmail(email: String!, password: String!, type: AuthUserType): AuthTokenInfo!
  logout(id: String): Boolean!
  refreshToken: AuthTokenInfo!
  forgotPassword(email: String!, type: AuthUserType): Boolean!
  resetPassword(token: String!, password: String!): Auth!
  verifyEmail(token: String!): Boolean!
  resendVerificationEmail: Boolean!
}
